### ISSUE TITLE
[BUG] Where is this file XLink/XLinkTime.h ?

### ISSUE THREAD

**Issue by christiangda** [luxonis/depthai-core#1007]
**Describe the bug**

I compile `depthai-core` (from github main branch)  for android, until here everything is Ok,  then trying to use it on my Native Android App, I got the following error

```bash
  .....app/src/main/cpp/include/depthai/xlink/XLinkStream.hpp:20:10: fatal error: 'XLink/XLinkTime.h' file not found
  #include <XLink/XLinkTime.h>
           ^~~~~~~~~~~~~~~~~~~
```

**Minimal Reproducible Example**
There is no minimal, sorry, to long to be explained here

**Expected behavior**
Find the file `XLink/XLinkTime.h` in the repository [github.com/luxonis/XLink/tree/master/include/XLink](https://github.com/luxonis/XLink/tree/master/include/XLink)

**Comment by themarpe** [comment]
@christiangda 
It is under `develop` branch - https://github.com/luxonis/XLink/tree/develop/include/XLink

For exact specific commit, see: 
```
hunter_config(
    XLink
    VERSION "luxonis-2021.4.2-xlink-linkid-race-fix"
    URL "https://github.com/luxonis/XLink/archive/e9eb1ef38030176ad70cddd3b545d5e6c509f1e1.tar.gz"
    SHA1 "b1e4ded41cd7b9c37189468e2aaddbb10cbda9f6"
    CMAKE_ARGS
        XLINK_ENABLE_LIBUSB=${DEPTHAI_ENABLE_LIBUSB}
)
```

under `cmake/Hunter/config.cmake`
