### ISSUE TITLE
Issues finding XLinkPublicDefines.h

### ISSUE THREAD

**Issue by jonasfehr** [luxonis/depthai-core#116]
Hi, I am trying to integrate compiled dynamic libraries into a project in Xcode based on openframeworks. But I run into a wall, as the compiler cant find the XLinkPublicDefines.h, included in the XLinkConnection.h file (#include <XLink/XLinkPublicDefines.h>
) Can you may help me how to procede? What details of information do you need from me, in order to help me?

**Comment by themarpe** [comment]
Hi @jonasfehr.

If you aren't using CMake to integrate the library (preferred) - then you'll have to add the necessary dependencies (include paths) as well.

These are:
 - include/depthai/
 - include/depthai-shared
 - include/depthai-shared/3rdparty
 - include/depthai-bootloader-shared
 - lib/cmake/depthai/dependencies/include
 
 Above paths are relative to installation directory (by default [build_dir]/install)
