### ISSUE TITLE
libusb is required

### ISSUE THREAD

**Issue by MikaMaracuja** [luxonis/depthai-core#121]
When compiling under debian buster, I got stuck into

```
CMake Error at XLink.cmake:27 (message):
  libusb is required
Call Stack (most recent call first):
  CMakeLists.txt:8 (include)
```

after running 

`sudo apt-get -y install cmake libusb-1.0-0-dev build-essential`

the compile process went almost through.

**Comment by themarpe** [comment]
Hi @MikaMaracuja 
Is this on latest `main` branch?
Can you retry on `develop` - otherwise a known fix which was needed in the past is to create a symlink to /usr/lib for libusb shared library. Although shouldn't be needed anymore. 
I presume this is on Raspberry PI?

**Comment by MikaMaracuja** [comment]
Its on debian buster.
