### ISSUE TITLE
c_streams_myriad_to_pc is not thread safe, and prevents multiple cameras from connecting with varying resolutions

### ISSUE THREAD

**Issue by Procdox** [luxonis/depthai-core#18]
c_streams_myriad_to_pc is modified as part of create_pipeline.
https://github.com/luxonis/depthai-core/blob/52695a85706a16372f4cc8ceef9a3552bd895acc/src/device.cpp#L931

Initializing a second camera with different parameters for most streams causes the second cameras parameters to be ignored.
I'm not sure what would happen for disparity_color, but I assume it's unintended behavior.

**Comment by Luxonis-Brandon** [comment]
Thanks for the report @Procdox !  Triaging.
