### ISSUE TITLE
Unreachable code in `dai::DataOutputQueue::get()` -- unclear intention

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai-core#284]
Unreachable code in `dai::DataOutputQueue::get()` -- the intention is unclear. Needs a review.
On line 175-6, do you want to throw, or return nullptr. Can't do both.

https://github.com/luxonis/depthai-core/blob/efa3deb7c17e223238696416cd45d2d3eb35674f/include/depthai/device/DataQueue.hpp#L171-L179

### Setup

* all OS
* all compilers
* depthai-core v2.13.2

### Repro

MSVC compiler told me it is unreachable.
Verified by code review. It is unreachable.

### Result

The code will throw. But it is unclear if that is the dev's intention.

### Expected

Code matches dev's intention.

**Comment by themarpe** [comment]
`return nullptr` is redundant in this case - the underlying queue was destructed in this case. 
If the underlying queue was destructed, then the caller is given the reason why and gets out of the blocked call.

**Comment by diablodale** [comment]
verified it is merged into `develop` codebase
