### ISSUE TITLE
The model path exists in Chinese, depthai_demo.py cannot run error

### ISSUE THREAD

**Issue by hello-word-yang** [luxonis/depthai-core#294]
There is Chinese in my model path, and an error is reported when loading the file model as shown in the figure below.

<img width="724" alt="E64FE236-71AD-4eb7-9B66-80D8FB07A910" src="https://user-images.githubusercontent.com/64824216/144779672-9a055ca6-f188-485d-8e11-3751e1d90b86.png">

We found that it was because the std::ifstream method failed to open a file with a Chinese path.

https://github.com/luxonis/depthai-core/blob/0cc6284767ae21e8747d26562cb058d181e0ca34/src/pipeline/AssetManager.cpp#L32

Can you help us solve this problem? thanks.

**Comment by Luxonis-Brandon** [comment]
Asking team.  Not immediately sure.

**Comment by themarpe** [comment]
Hi @hello-word-yang 
Seems like its a Windows specific issue. Checking on how to properly handle this for Windows platform...

**Comment by themarpe** [comment]
@hello-word-yang I think what might immediately remedy the issue is setting UTF-8 support in Locale under Windows settings.

![image](https://user-images.githubusercontent.com/16122143/145033635-ad2e5b7f-5ed8-4796-8e34-71076fe22b62.png)

(Source: https://pete.akeo.ie/2019/11/powershell-script-to-convert-utf-8.html)

Otherwise it seems like we have to handle the path as UTF-16 and use wide strings in Windows case...
Will look into adding clean support for that as well

**Comment by themarpe** [comment]
Note: this is a system wide change and may affect other software running on the computer. I advise to continue with precaution and rollback if undesired side effects show up

**Comment by hello-word-yang** [comment]
hi, @themarpe 

Thanks for your reply, I will test the method you mentioned as soon as possible.

**Comment by hello-word-yang** [comment]
hi, @themarpe 

After my test, after modifying the encoding format of the system to utf-8, depthai-demo.py can run normally when the model path contains Chinese path.

Thank you for the solution.

But I think it is better to solve this problem from the code level, because it is impossible for all users to modify the system.

**Comment by themarpe** [comment]
> But I think it is better to solve this problem from the code level, because it is impossible for all users to modify the system.

I agree - I wish Windows will push more into UTF-8 direction, so this won't be a platform dependent thing anymore. 
Will see how I'll be with time the next couple of weeks. Thanks for testing it out:)
