### ISSUE TITLE
Lack file 【depthai-bootloader-shared...】 and 【depthai-shared】

### ISSUE THREAD

**Issue by berlin2049** [luxonis/depthai-core#346]
dowanload it and copy to  folder【depthai-core\shared】 can solve it.

【depthai-core\shared】：https://github.com/luxonis/depthai-shared
【depthai-bootloader-shared...】：https://github.com/luxonis/depthai-bootloader-shared

**Comment by szabi-luxonis** [comment]
> dowanload it and copy to folder【depthai-core\shared】 can solve it.
> 
> 【depthai-core\shared】：https://github.com/luxonis/depthai-shared 【depthai-bootloader-shared...】：https://github.com/luxonis/depthai-bootloader-shared

You need to run `git submodule update --init --recursive` after cloning or clone with `git clone git@github.com:luxonis/depthai-core.git --recursive`

**Comment by berlin2049** [comment]
> > dowanload it and copy to folder【depthai-core\shared】 can solve it.
> > 【depthai-core\shared】：https://github.com/luxonis/depthai-shared 【depthai-bootloader-shared...】：https://github.com/luxonis/depthai-bootloader-shared
> 
> You need to run `git submodule update --init --recursive` after cloning or clone with `git clone git@github.com:luxonis/depthai-core.git --recursive`

these two command take to much time in the region i'm at

**Comment by szabi-luxonis** [comment]
> 

You can use `git clone git@github.com:luxonis/depthai-core.git --recursive --depth 1`, it will download the latest.
Total downloaded size is less than 1MB.
