### ISSUE TITLE
`dai::RawImgFrame::sequenceNum` is errant sign/unsigned -- wraparound and casting problems

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai-core#354]
I'm concerned that `dai::RawImgFrame::sequenceNum` doesn't match `ImgFrame::get/setSequenceNum()`.
They do not have matching sign types.
`dai::RawImgFrame::sequenceNum` is `int`
`ImgFrame::get/setSequenceNum()` are `unsigned int`

The sequencing number should have consistent var type across all usage. I am also concerned it is likely a 32-bit value..

### Setup

* all
* depthai-core `main`

### Repro

Found while I'm writing my frame sync code...

Of particular concern is when the sequence number is used for...sequencing. When `dai::RawImgFrame::sequenceNum` is incremented by (probably) the device and it reaches the maximum value of an `int` on that specific platform then ?something? will ?hopefully? restart the sequence at `0`. Or is that ?something? actually operating with an `unsigned int` like the APIs and will therefore continue above the max value of an `int` which is then interpreted as a set of negative numbers because the API casts it unto an unsigned int? This likely breaks sequencing logic in apps.

The size of the sequence number is also of concern. I thing 32-bit is too small.

max int 32-bit | 2147483647
-- | --
seconds at 60fps | 35791394.1
mins | 596523.235
hours | 9942.05392
days | 414.252247
years | 1.13493766

It is very possible for a device to run 1.1 years. And then would encounter this issues behaviors.
If instead the sequence number was a 64-bit int (signed or unsigned), we no longer have a wraparound issue.

max int 64-bit | 9,223,372,036,854,770,000
-- | --
seconds at 60fps | 1.53723E+17
mins | 2.56205E+15
hours | 4.27008E+13
days | 1.7792E+12
years | 4874520145

### Suggestion

Change everything with sequencing to `int64_t`. The unsigned is not needed and in general is discouraged in modern c++.
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-nonnegative

**Comment by themarpe** [comment]
Thanks for the report.

We'll most likely address when refactoring messages - otherwise not a high priority currently.
