### ISSUE TITLE
feature req: add function chaining to all `set...()` functions -- return `T&`

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai-core#356]
I request all `set...()` functions to support function chaining by returning a reference to themselves.
This is widely used across languages. Can be used both in C++ and in python bindings (python loves these).
Could combine with #355 as a task "make get() const and set() return T&"

```c++
myColorImgFrame.setCategory(2).setWidth(500).setHeight(200);
// or everything with rvalues
myfunc(myqueue->get<dai::ImgFrame>().setCategory(2).setWidth(500).setHeight(200));
```

Fixes are trivial

```c++
// old
void ImgFrame::setCategory(unsigned int category) {
    img.category = category;
}

// new
ImgFrame& ImgFrame::setCategory(unsigned int category) {
    img.category = category;
    return *this;
}
```

### Setup

* all

### Repro

Found while writing my app and having to make temp variables just to `set...()` some things.

**Comment by themarpe** [comment]
Thought about it as well, I think it will fit nicely.
Will address soon
