### ISSUE TITLE
Build depthai-core fils on Ubuntu 20.04 when BUILD_SHARED_LIBS = on

### ISSUE THREAD

**Issue by Skammi** [luxonis/depthai-core#376]
When building depthai-core core on Ubuntu 20.04 it fails with a link error.
Process followed:
`git clone https://github.com/luxonis/depthai-core`
`cd depthai-core/`
`git submodule update --init --recursive`
`cmake -S. -Bbuild -D'BUILD_SHARED_LIBS=ON'`
`cmake --build build --parallel 7`

Results in:
`...`
`Linking CXX shared library libdepthai-core.so
/usr/bin/ld: /home/jac/.hunter/_Base/9b4e732/64dcd41/90457df/Install/lib/libspdlog.a(spdlog.cpp.o): relocation R_X86_64_TPOFF32 against _ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC`
`collect2: error: ld returned 1 exit status`
`make[2]: *** [CMakeFiles/depthai-core.dir/build.make:917: libdepthai-core.so] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:513: CMakeFiles/depthai-core.dir/all] Error 2`
`make: *** [Makefile:141: all] Error 2`

The Top level CMakeLists.txt files seems to want to take care of the flag in line 10.
`if(BUILD_SHARED_LIBS)`

**Comment by Skammi** [comment]
Solved the problem by deleting the ~/.hunter directory. 
I had build an earlier version without the BUILD_SHARED_LIBS on.
I would suggest to keep al object used in the build within the depthia-core/build directory. So when you rebuild or want to add an option removing the build directory is sufficient.

**Comment by themarpe** [comment]
@Skammi thanks for the report - currently some changes to build flags required by `BUILD_SHARED_LIBS=ON` aren't cached properly by Hunter. We'll have to address this or move it to build directory as you've mentioned.
