### ISSUE TITLE
cmake fails, missing data_writer.cpp

### ISSUE THREAD

**Issue by jhurliman** [luxonis/depthai-core#39]
```
CMake Error at CMakeLists.txt:60 (add_library):
  Cannot find source file:

    /home/jhurliman/Code/depthai-core/shared/depthai-shared/src/general/data_writer.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at CMakeLists.txt:60 (add_library):
  No SOURCES given to target: depthai-core
```

**Comment by themarpe** [comment]
Hi @jhurliman 
Have you made sure to initialize submodules using? 
```
git submodule update --init --recursive
```
And make sure you are using the right branch (gen2 is on `gen2` and `gen2_develop` for cutting edge)

**Comment by sfmajors373** [comment]
I'm trying to build an Arch Linux AUR package for this so I am building from the tar balls, which means the above solution does not work for me.  Do you have a suggestion for how to fix this issue when building from tar balls?

**Comment by themarpe** [comment]
@sfmajors373 Unfortunately as far as I'm aware, Github does not serve tarballs which include submodules. 
One option would be to download the tarballs of the references submodules separatelly and extract them into required directory.
We'll most likely add a download to a complete tarball (with submodules) on releases.

**Comment by themarpe** [comment]
@jhurliman Error was presented with a more user friendly message in f8d034785aea920c1ff047dd8b43785fdb6eff52.
Note that the repository still requires to be cloned to get the needed submodules.
Final complete source tar/zips are going to be created for releases

**Comment by Luxonis-Brandon** [comment]
Thanks!

**Comment by themarpe** [comment]
@sfmajors373 and @jhurliman 
As mentioned, releases now contain both .zip and .tar.gz which includes the submodules as well.
https://github.com/luxonis/depthai-core/releases/tag/v2.0.0
Hope this enables your usecases better :)
