### ISSUE TITLE
host console spammed on correct+typical device close/shutdown -- I expect nothing in console

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai-core#413]
When a device is correctly closed and `DEPTHAI_LEVEL=ERROR` , the console has spam from xlink/device.
My expectation is no console output unless there is an error, i.e. a condition that is unexpected, unplanned, or undesired which results in wrong program operation, wrong values, program faults, etc.

```
F: [global] [         0] [EventRead00Thr] dispatcherEventReceive:94     Duplicate id detected. 
```

### Setup

* Microsoft Windows [Version 10.0.19044.1526]
* depthai-core v2.15.0
* VS v16.11.10

### Repro

1. Create, compile any depthai app that sets `DEPTHAI_LEVEL=ERROR`. Try the sdk's `tests/image_manip_node_test`
2. Run the app and watch the console as the app nicely closes the device.

### Result

```
F: [global] [         0] [EventRead00Thr] dispatcherEventReceive:94     Duplicate id detected. 
```

Also errant in that the `Duplicate id detected` text in the message is not useful.
Also errant in that its format is completely different than typical log entries `[14442C10C1A1C6D200] [13.513] [system] [info] ImageManip allocated resources: shaves: [15-15] no cmx slices.`

### Expected

No console output.
Because there was no fault, error, invalid data, etc.

I found this while writing testing automation tools. These misleading and unexpected format log messages pollute the log/console collection. If a console message must be force displayed in the console when device is nicely closed, then it should say `Device correctly closed.` and it should be in the single unified log output format. But it would be strange to write `[fatal]` for a "correct" log entry. This further suggests this message should never appear.

```
[14442C10C1A1C6D200] [13.513] [system] [fatal] Device correctly closed.
```

### Notes

These are from xlink and use their own logging mechanism. An additional related issue is that the method by which xlink writes to the console is not in synchronization with spdlog, not thread safe, and therefore corrupts the spd logs. I have forever seen my console logs having a mix of xlink and spdlog writing over each other simultaneously. This naturally corrupts the log messages and prevent correct structured collection.

**Comment by themarpe** [comment]
Thanks @diablodale 

We got this one in the pipeline to be fixed. I'll include it in 2.15.1.
