### ISSUE TITLE
valid mesh file sends warning to log double marked both [warning] and [info]

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai-core#436]
Recent versions of depthai-core when used with valid mesh files is sending errant log entries.
In my app, these errant log entries are causing my log callback for error detection to misfire.

```
[192.168.2.23] [3499.697] [StereoDepth(5)] [warning] [info] Rectification mesh loaded, will override camera intrinsics/extrinsics matrices
```

### Setup

* depthai-core v2.15.1
* Microsoft Windows [Version 10.0.19044.1586]
* VS2019 v16.11.11

### Repro

1. create, build an app with StereoDepth, and loads mesh data.
2. Start the app

### Result

```
...
[192.168.2.23] [3499.697] [StereoDepth(5)] [warning] [info] Rectification mesh loaded, will override camera intrinsics/extrinsics matrices
...
```

That spdlog entry is level=WARN. My callback is receiving it.
Its spdlog payload has the string "[info]" at the start of it. Unknown how that string got into the payload.
Naturally, this is not be a warning. This is correct operation and therefore should be level=debug or level=info.

### Expected

Nothing unless I set `DEPTHAI_LEVEL=debug`

**Comment by themarpe** [comment]
Thanks for the report - was a debugging leftover. Addressed in latest `develop`
