### ISSUE TITLE
the artifact server seems to be broken

### ISSUE THREAD

**Issue by windelbouwman** [luxonis/depthai-core#446]
During CMake, an artifactory site is used, but it returns a 500 error for me:

https://artifacts.luxonis.com/artifactory/luxonis-myriad-release-local/depthai-bootloader/

The error response shown:

```json
{
  "errors" : [ {
    "status" : 500,
    "message" : "Artifactory failed to initialize: check Artifactory logs for errors."
  } ]
}
```

**Comment by cafemoloko** [comment]
thanks for reporting @windelbouwman . The artifactory seems to be up and running again.
