### ISSUE TITLE
[Compilation Error] Got CMake Error at shared/depthai-bootloader-shared.cmake:33

### ISSUE THREAD

**Issue by shoufei403** [luxonis/depthai-core#489]
version: depthai-core-v2.15.4
error info:
```bash
CMake Error at shared/depthai-shared.cmake:39 (if):
  if given arguments:

    "STREQUAL" "-"

  Unknown arguments specified
```
```bash
CMake Error at shared/depthai-bootloader-shared.cmake:33 (if):
  if given arguments:

    "STREQUAL" "-"

  Unknown arguments specified
```

I comment where error happen, then compilation success.
The errors happen in `shared/depthai-bootloader-shared.cmake` and `shared/depthai-shared.cmake`.
Comment the content:
```cmake
        #string(SUBSTRING ${statusCommit} 0 1 status)
        #if((${status}) STREQUAL "-")
        #    message(FATAL_ERROR "Submodule 'depthai-bootloader-shared' not initialized/updated. Run 'git submodule update --init --recursive' first")
        #endif()
```
Can you check this out?

**Comment by szabi-luxonis** [comment]
@shoufei403 Run 'git submodule update --init --recursive' first if you cloned the repo with git

**Comment by shoufei403** [comment]
Thanks for your responding. Actually, I download from [https://github.com/luxonis/depthai-core/releases/tag/v2.15.4](https://github.com/luxonis/depthai-core/releases/tag/v2.15.4).

**Comment by szabi-luxonis** [comment]
Then you need to download all subsequent submodules, manually and place it in `shared` folder.
https://github.com/luxonis/depthai-bootloader-shared/tree/f244f51f07e7ffd87ee0a777a0b54cd837857709
https://github.com/luxonis/depthai-shared/tree/8cf8caab2a848ced60791dda384839cefe6dab6d

**Comment by themarpe** [comment]
@shoufei403 
To download a specific version - download it under releases. It already includes packed shared submodules. See: https://github.com/luxonis/depthai-core/releases/download/v2.15.4/depthai-core-v2.15.4.tar.gz (under assets of 2.15.4 Releases)

**Comment by shoufei403** [comment]
Got it. Thanks for you guys help.
