### ISSUE TITLE
libarchive build fails on Android

### ISSUE THREAD

**Issue by Bercon** [luxonis/depthai-core#513]
Hunter fails trying to build libarchive on Android. I think this is fairly recent issue possibly with dependencies / build environment, because couple weeks ago my builds passed without issues on same v2.16.0 depthai-core version and today I get this

```
In file included from /home/jerry/.hunter/_Base/cb0ea1f/f05d2ab/528716a/Build/libarchive-luxonis/Source/libarchive/archive_digest.c:In file included from /home/jerry/.hunter/_Base/cb0ea1f/f05d2ab/528716a/Build/libarchive-luxonis/Source/libarchive/archive_entry_sparse.c:30:
/home/jerry/.hunter/_Base/cb0ea1f/f05d2ab/528716a/Build/libarchive-luxonis/Source/libarchive/archive.h:101:10: fatal error: 'android_lf.h' file not found
#include "android_lf.h"
         ^~~~~~~~~~~~~~
```

Possibly related https://github.com/libarchive/libarchive/issues/890

**Comment by ibaiGorordo** [comment]
I haven't faced that issue, so I am not sure what the solution might be. But in case it helps, here is a Dockerfile for building the library in Android. It is based on the TFLite Dockerfile, so it probably has a lot of unnecessary code but it builds the library correctly:
https://gist.github.com/ibaiGorordo/ebfdb97cbd29a3bccea19040f96f8f34

**Comment by Bercon** [comment]
This turned out to be my mistake. I had accidentally rolled back the depthai-core version prior to v2.16.0 which didn't have Android support yet and thus obviously failed
