### ISSUE TITLE
[Feature Request] ColorCamera setNumFramesPool

### ISSUE THREAD

**Issue by Erol444** [luxonis/depthai-core#519]
**Start with `why`:**
When working with high-res frames (eg. 48MP), you quickly run out of RAM. I believe by default, ColorCamera has pool size for 4 frames, and each "48MP frame" consumes ~48MB (`6000×5312×1,5`), together almost 200MB. Having a simple `cam.isp -> XLinkOut`  pipeline consumes `300MB/340MB` DDR, so there isn't much space for anything else (eg. NN). Trying to use NN will result in errors like below:

```
[NeuralNetwork(5)] [error] Tried to allocate '13199936'B out of '575615'B available.
```

**Move to `what`:**
Add `setNumFramesPool` support to ColorCamera, to either reduce RAM consumption or to have more frames for eg. syncing purposes ([current workaround here](https://github.com/luxonis/depthai-experiments/blob/master/gen2-face-recognition/main.py#L120-L127)).

**End with `how`:**
Magic :magic_wand: coupled with great engineering

**Comment by themarpe** [comment]
Done - in `develop` :)
