### ISSUE TITLE
[Feature request] TrackedFeatures `.getTimestamp()` and `.getSequenceNum()`

### ISSUE THREAD

**Issue by Erol444** [luxonis/depthai-core#539]
### Start with the `why`:

So we can sync (either via timestamp or sequenceNum) tracked features with color frame, depth frame, NN output, etc. I believe timestamps should be added to all depthai messages (so to `Buffer`, so all messages have them?). Thoughts?

### Move to the `what`:

Add timestamps and sequence numbers to `TrackedFeatures`.

### Move to the `how`:

Likely just copy the timestamp/sequence number from the frame these features were generated from.

**Comment by szabi-luxonis** [comment]
@Erol444 Implemented in https://github.com/luxonis/depthai-core/pull/545
Please report back on expected behaviour, including on-device python bindings
