### ISSUE TITLE
zero_copy branch example code

### ISSUE THREAD

**Issue by 0y8w1x** [luxonis/depthai-core#542]
I just wanted to ask if there is an example code snippet, on how to use this branch, because I heard I need to use special functions. I got told by @Luxonis-Erik that opening an issue might give me an answer.

**Comment by Luxonis-Brandon** [comment]
Thanks.  We'll circle back.  I don't recall the context of this.  Will ask.

**Comment by moratom** [comment]
Hi @0y8w1x,
if you checkout the [branch](https://github.com/luxonis/depthai-core/tree/message_zero_copy), all output queues (the return value of the `device.getOutputQueue(...)`) will automatically have the zero-copy functionality.

I'm not sure how tested it is and if there are any known issues with the implementation, so CC: @themarpe  regarding this.

**Comment by themarpe** [comment]
@0y8w1x 
Main thing to note there is that the data isn't available through regular `getData` means but through `packet->data` instead. Also, `getFrame` & `getCvFrame` and other message helpers aren't available. 

This branch is experimental / feature testing branch, and it might or might not be upstreamed one day - it also isn't inteded for regular consumption, but for those working at the very edge of compute / latency / overhead boundaries.

**Comment by 0y8w1x** [comment]
thanks @themarpe and @moratom for clarifying. I guess I need to go through the commits, to create a working example then 👍
