### ISSUE TITLE
[BUG] IMU coordinate?

### ISSUE THREAD

**Issue by dongxuanlb** [luxonis/depthai-core#578]
<img src="https://user-images.githubusercontent.com/865803/188527075-69132026-fbc0-4976-a2df-4fb37445126c.png" height=240>
the oakd device is placed normally。

<img src="https://user-images.githubusercontent.com/865803/188527093-0a3f7f08-b8dc-4c2c-bf08-52cbfa29f2cb.png" height=240>
the accel output by the “depthai-core/examples/IMU/imu_gyroscope_accelerometer.cpp" is :
x: -10, y: 0.5, z: 0.4

My quest is:
1. the default coordinate like opencv, or realsen is like:
<img src="https://user-images.githubusercontent.com/865803/188527214-41bf2126-ce9a-4d1d-aa8c-97e8b0cb4117.png" height=240>
<img src="https://user-images.githubusercontent.com/865803/188527231-265c45c3-654a-43e3-9ee6-ac32a54b59bd.png" height=240>

y axis is the gravity. but the oakd is x axis?

2. the gravity maximum value should not exceed 10，does the device's imu need to be calibrated?

**Comment by szabi-luxonis** [comment]
@dongxuanlb 
1. Yes.
2. Yes, needs calibration. At the moment we don't perform factory calibration for IMU.
