### ISSUE TITLE
[BUG] Cant build with OPENCV support

### ISSUE THREAD

**Issue by an99990** [luxonis/depthai-core#607]
I have followed this tutorial to install opencv in my RPI : https://pyimagesearch.com/2018/09/26/install-opencv-4-on-your-raspberry-pi/ without the virtual environment part. So i installed opencv globally.
However, when I am building depthai_core cmake seems to be unable to build with OPENCV Support. It does not find opencv.

Can you guys guide me on how to resolve this ?

**Comment by an99990** [comment]
hi @themarpe, thank you for your answer
What path exactly should i link ?
I just tried in depthai-core/build

`cmake -S . -B build -D OpenCV_DIR=/home/ubuntu/opencv-3.4.9/cmake/ `
and got the same results

**Comment by themarpe** [comment]
@an99990 the path to lib/cmake/opencv.

Example:
```
/opencv-4.5.1/build/install_dir/lib/cmake/opencv4
```

+ it seems you are pointing to OpenCV3. Only OpenCV4 is supported

**Comment by an99990** [comment]
indeed i was giving the wrong path thank you
