### ISSUE TITLE
Cannot find file depthai_wrapper.hpp

### ISSUE THREAD

**Issue by kishordurve** [luxonis/depthai-core#641]
I am trying out the example at https://github.com/luxonis/depthai-core/blob/rgb-alignment/example/main.cpp. The file has '#include "depthai/depthai_wrapper.hpp"' as the first line. I could not find depthai_wrapper.hpp in any of the include sub folders. Can someone please help out?

**Comment by themarpe** [comment]
CC: @saching13

**Comment by saching13** [comment]
https://github.com/luxonis/depthai-core/blob/rgb-alignment/include/depthai/depthai_wrapper.hpp
Here. 
This is a gen-1 code. Everything here can be done in Main and on-device. So I suggest against using this.

**Comment by kishordurve** [comment]
Thank you.

Regards,

Kishor Durve
