### ISSUE TITLE
[Question / Feature-Request] access image data without opencv support?

### ISSUE THREAD

**Issue by artificiel** [luxonis/depthai-core#658]
### Start with the `why`:
I don't need opencv functions and try to streamline my dependencies and build process

### Move to the `what`:
openCV it is required to getFrame()

### Move to the `how`:
is there a method to get the image data without activating openCV support? if so is how is the data packed, and is there an example?

**Comment by themarpe** [comment]
Hi @artificiel 

Sure, this is supported "out of the box". You may explicitly disable OpenCV Support using `-D DEPTHAI_OPENCV_SUPPORT=OFF`.

You can get data out using getData() paired with retrieving getWidth, getHeight, getType.
Refer to `depthai-core/src/opencv/ImgFrame.cpp` for EXACT step by step on how that happens (if you skip OpenCV parts)
