### ISSUE TITLE
[update/rebase the UVC branch to latest] {update/rebase the UVC branch to latest?}

### ISSUE THREAD

**Issue by awida1** [luxonis/depthai-core#670]
### Start with the `why`:
UVC branch is not up to date and cannot use features like GPIO 

### Move to the `what`:
update/rebase the UVC branch to latest

### Move to the `how`:
Update branch

**Comment by Erol444** [comment]
cc @themarpe whether we have a plan to updaet the UVC branch (or perhaps merge it:)?

**Comment by themarpe** [comment]
@awida1 
Updated with state of latest `develop`

**Comment by awida1** [comment]
@themarpe Thank you for that. I ran the "install_requirements.py" and I am getting an error "'depthai.Pipeline' has no attribute 'createUVC'"

**Comment by themarpe** [comment]
@awida1 

That API is deprecated. Use `pipeline.create(dai.node.UVC)`

**Comment by awida1** [comment]
Thank you for the reply. I am getting: AttributeError: module 'depthai.node' has no attribute 'UVC'

**Comment by awida1** [comment]
Also what is included in the devlop branch that was updated? I assume GPIO. Anything else? I am trying to get a project working and some areas of UVC need support like video rotation. Are any of these included? Is there a place that I can see the updates? 

Thanks!

**Comment by themarpe** [comment]
You can check updates here: https://github.com/luxonis/depthai-core/releases

Nothing to relation to UVC was changes, just mainlined.

For that you might want to checkout ImageManip node, which could perform such operation

**Comment by awida1** [comment]
I changed the "uvc = pipeline.createUVC()" to "pipeline.create(dai.node.UVC)" 

but I am getting the  "AttributeError: module 'depthai.node' has no attribute 'UVC'" error

**Comment by Erol444** [comment]
@awida1 have you installed the latest depthai library from `gen2_uvc` branch?

**Comment by awida1** [comment]
I did an "install requirements" from the gen2_UVC branch. I assume it grabs the correct one? Is that the one youre talking about?

**Comment by awida1** [comment]
Maybe I am getting the syntax wrong. Is there a UVC example I can run.
