### ISSUE TITLE
[BUG] {Read IMU data from OAK-D-SR failed}

### ISSUE THREAD

**Issue by yuannuaa** [luxonis/depthai-core#733]
**Describe the bug**
When i try IMU/imu_gyroscope_accelerometer.py from OAK-D-SR, i got 
`[18443010912F5E1200] [1.3] [2.225] [IMU(0)] [critical] IMU driver failed with error code 1. Your board likely doesn't have IMU! `

**Minimal Reproducible Example**
The version of Depthai is 2.20.2.0.
The code is from [https://github.com/luxonis/depthai-python/blob/main/examples/IMU/imu_gyroscope_accelerometer.py](imu_gyroscope_accelerometer.py)

**Expected behavior**
I want to obtain the inertial information form OAK-D-SR

**Screenshots**
![image](https://user-images.githubusercontent.com/14670803/221446387-8d8f1361-c6df-48e6-8a06-d6895f57f1a6.png)

**Comment by Luxonis-David** [comment]
@yuannuaa thanks for reporting. 
Unfortunately we found out that we have an error on HW thus this bug can't be resolved on EA OAK-D-SR batch on FW side.
If you need IMU for your application please shoot an email to support@luxonis.com and we will arrange reworked sample as a replacement. 
Thanks for understanding!
