### ISSUE TITLE
[Feature-Request] BNO08x sequence should not wrap

### ISSUE THREAD

**Issue by chengguizi** [luxonis/depthai-core#738]
### Start with the `why`:
It appears that BNO085 sequence only goes from 0-255 and wrap around. Is that expected? BMI270 didn't has this behaviour

### Move to the `what`:
BNO085 should have a more sensible sequence number to output to host

**Comment by szabi-luxonis** [comment]
Added workaround in: https://github.com/luxonis/depthai-core/commit/37b1cc599161b7f35d86c4a6d4b4c0df2b3d94a8
