### ISSUE TITLE
[Feature-Request] {On-device Pointcloud NN model with C++ example}

### ISSUE THREAD

**Issue by FredCormiers** [luxonis/depthai-core#756]
Give an example of the "On-device Pointcloud NN model" in C++ to facilitate the creation of point clouds. 

The explanation are here : https://docs.luxonis.com/en/latest/pages/tutorials/device-pointcloud/

The python code are here : https://github.com/luxonis/depthai-experiments/tree/master/gen2-pointcloud/device-pointcloud

**Comment by Erol444** [comment]
Hi Fred, we plan to add Poitncloud node to the depthai, which means this NN-based approach would be irrelevant. More [information here](https://github.com/luxonis/depthai-core/issues/791).
