### ISSUE TITLE
Cannot stream depth and disparity together on gen2 pipleline.

### ISSUE THREAD

**Issue by kota-rr** [luxonis/depthai-core#76]
`disparity` stream is collapsed if `depth` is streamed. on `gen2`. 

This can be reproduced by setting `outputDepth` flag of the stereo example. 
https://github.com/luxonis/depthai-core/blob/gen2_develop/examples/src/stereo_example.cpp

This is so regardless of `lrcheck`, `extended`, and, `subpixel` flags.

**Comment by alex-luxonis** [comment]
Yes, this is a current limitation for the standard mode (`lrcheck`, `extended` and `subpixel` all disabled), and for `subpixel` mode. However, both `disparity` and `depth` should work for `lrcheck` and/or `extended`.

For the standard mode we have a fix, I will open a PR soon.
For the subpixel mode, an optimization is enabled on device side that combines subpixel processing with the conversion to depth, so if the depth output is enabled, disparity won't be available. We'll look later if possible to separate them.
