### ISSUE TITLE
`stability_stress_test` fails to link on Ubuntu: libpthread.so.0: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai-core#769]
`test/stability_stress_test` fails to link on Ubuntu 20.04 with gcc10. It can not find pthreads.
I believe this is due the custom cmake code for `test/stability_stress_test` missing `Threads::Threads` link library.

### Setup

* Ubuntu 20.04.5 LTS
* gcc-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
* depthai-core `develop` at e5dae8fd2f9e543bd99f9d1a73959398ef5bd0b4
* depthai-shared `develop` at 5988f9629d9c04ba48fa938d62443d49416c6d35

### Repro

Config and build for: Debug, shared libs, opencv support, build tests

### Result

```
[74/275] Linking CXX executable tests/stability_stress_test
FAILED: tests/stability_stress_test
: && /usr/bin/g++-10  -g  -Wl,--export-dynamic  -rdynamic tests/CMakeFiles/stability_stress_test.dir/src/stability_stress_test.cpp.o  -o tests/stability_stress_test  -Wl,-rpath,/usr/local/src/build  libdepthai-core.so && :
/usr/bin/ld: tests/CMakeFiles/stability_stress_test.dir/src/stability_stress_test.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

### Expected

All files build and link with no errors.

### Fix

I can fix this issue by adding `Threads::Threads` to the end of lines 270 and 273

https://github.com/luxonis/depthai-core/blob/c2b96c81f11bbd3625cbd18c634c60a969b675c3/tests/CMakeLists.txt#L269-L273

**Comment by themarpe** [comment]
@diablodale if you have the fix in place feel free to open a PR and will merge. Thanks for the report!
