### ISSUE TITLE
port for pyserial for serial communication oak ffc 4p 

### ISSUE THREAD

**Issue by Maimilian** [luxonis/depthai-core#789]
Hi, I am in process of implementing serial communication in my code using pyserial. Here, I would like to know which port I have to select. I think it is usually something like _/dev/serial0_ . You will see in the picture that I use the rx and tx pins of the aux-part of the board. 
I hope someone can help me with the port! Thanks a lot!
![728D9335-B106-4EA4-9176-CD5A008C8337](https://user-images.githubusercontent.com/129183966/228245256-bd9c364e-6f86-4eca-bb77-6b39ab3537b5.png)

**Comment by themarpe** [comment]
CC @Erol444 I assume this will be the example you've created https://github.com/luxonis/depthai-python/pull/811
@Maimilian
