### ISSUE TITLE
GCC13 compatibility: XLinkStream.hpp needs to include stdexcept for std::runtime_error

### ISSUE THREAD

**Issue by MarioSavu** [luxonis/depthai-core#833]
The issue and solution are straight forward, an #include <stdexcept> should be added in XLinkStream.hpp, and then gcc13 will compile the file.
Otherwise you'll see errors as this: 
....../depthai-test/depthai-core/include/depthai/xlink/XLinkStream.hpp:81:47: error: expected class-name before ‘{’ token
   81 | struct XLinkError : public std::runtime_error {

**Comment by MarioSavu** [comment]
I tried pushing a branch with a fix to open a PR when I opened this issue, but I don't have write permissions, so instead I'll just say that you should modify this https://github.com/luxonis/depthai-core/blob/main/include/depthai/xlink/XLinkStream.hpp#L16 to include this: `#include <stdexcept>`

**Comment by themarpe** [comment]
Resolved in `develop` and `main` now as well
