### ISSUE TITLE
`fatal error: depthai/depthai.hpp: No such file or directory` when integrating into ROS package

### ISSUE THREAD

**Issue by mheyrman** [luxonis/depthai-core#844]
Hello,

I have a fairly fleshed out ROS controller (ROS2 humble in Ubuntu 22.04) for a robot and I am trying to integrate an Oak-D camera to use get depth data. However, when building, I run into the following error:

> fatal error: depthai/depthai.hpp: No such file or directory
> #include "depthai/depthai.hpp

I am adding it in CMakeLists.txt as follows:

> find_package(depthai CONFIG REQUIRED HINTS "${CMAKE_CURRENT_SOURCE_DIR}/depthai-core/build")
> if(depthai_FOUND)
>   message(WARNING "depthai FOUND, Version:" ${depthai_VERSION} " directory: " ${depthai_DIR})
> endif()`

which shows that depthai Version 2.21.2 is being found when building, and have it included to the `ament_target_dependencies` and have `depthai::opencv` in `target_link_libraries`, as specified in the integration docs. 

I have no idea what's causing this issue or how to address it after debugging for a day. Help would be appreciated.

Update: I've figured out that this issue is fixed by explicitly defining the `include_directories` and pointing to `${depthai_DIR}/install/include`. But now there's another issue that `Serialization.hpp`, an indirect dependency of depthai.hpp cannot find `nop/serialization.h`, which is located in the `lib` folder's dependencies.

**Comment by themarpe** [comment]
Hi @mheyrman 

I'd double check first that correct targets link to correct depthai. Also, make sure that depthai on the ither side is built.

Another thing to try is to install depthai core first to any location (can be under the default build/install) and to point to that instead of build.
