### ISSUE TITLE
Question about specTranslation params

### ISSUE THREAD

**Issue by borongyuan** [luxonis/depthai-core#847]
The release note of v2.21.2 mentioned:
> Added disparityToDepthUseSpecTranslation, rectificationUseSpecTranslation, and depthAlignmentUseSpecTranslation options for advanced usage

Looks like their default values are:
```
bool disparityToDepthUseSpecTranslation = true;
bool rectificationUseSpecTranslation = false;
bool depthAlignmentUseSpecTranslation = true;
```
I don't understand why calibration data is not used as default for `disparityToDepth` and `depthAlignment`.
Not sure if these are related to #840. I didn't see a noticeable effect in my tests.

**Comment by Erol444** [comment]
Hi @borongyuan , I believe it really depends on the calibration quality. Usually, you will have more accurate translation if you look at specs (CAD model) than the one obtained from camera matrix. But for rectification we found that we obtained better results if we took extrinsics from calibration.

**Comment by borongyuan** [comment]
Thanks, I get it.
