### ISSUE TITLE
[BUG] { Failed to compile layer "/ScatterND": unsupported layer type "ScatterNDUpdate"}

### ISSUE THREAD

**Issue by friend045** [luxonis/depthai-core#858]
An error occurred while converting OpenVINO to a blob.

Failed to compile layer "/ScatterND": unsupported layer type "ScatterNDUpdate"

![螢幕擷取畫面 2023-06-26 084052](https://github.com/luxonis/depthai-core/assets/19499221/db32432e-90e4-460d-acd5-fab6c48a9bad)

[Link](https://drive.google.com/drive/folders/1L3_CjImVm8CqAwb_mckLl_aq-95m6mNc?usp=drive_link)

**Comment by themarpe** [comment]
@friend045 you'll have to file a bug over at OpenVINO for this. Cc: @tersekmatija
