### ISSUE TITLE
Number of connections limited to 32

### ISSUE THREAD

**Issue by aashutoshpy** [luxonis/depthai-core#909]
I saw that the number of device connections are limited to 32 by hard-coding, wanted to know if there is any reason behind this. Can I increase it and re-compile the library without any issue?

https://github.com/luxonis/depthai-core/blob/82ab07d037c02f56042d1d2d55a718f379651ed9/src/xlink/XLinkConnection.cpp#L119C13-L119C13

**Comment by themarpe** [comment]
@aashutoshpy no issues with bumping that up - main reason for it is the XLink's dependency limit (used to be 32): https://github.com/luxonis/XLink/blob/master/include/XLink/XLinkPrivateDefines.h#L121

Feel free to open a PR to bump to 64. Other option would be moving this define to public defines in XLink and then relying on that instead, but not needed atm
