### ISSUE TITLE
[Feature-Request] Camera - IMU synced in Sync Node

### ISSUE THREAD

**Issue by michaelnguyen11** [luxonis/depthai-core#930]
### Start with the `why`:
Camera-IMU messages synchronization are very important in VIO/SLAM development.

### Move to the `what`:
A pull request #917 implemented a Sync Node that synchronized timestamp of camera left/right/center on device then send to host for display. It would be nice if the IMU data can be synchronized with camera data.

### Move to the `how`:
I don't have any idea to implement that yet.

Hi @asahtik ,

Know that you are the author of pull request #917 . Do you have any plans to support the IMU data to be synchronized with camera data through the Sync Node and Message Groups? Thank you in advance!

Best regards,
Hiep Nguyen

**Comment by asahtik** [comment]
Hi @michaelnguyen11, great question. Currently the Sync node synchronizes a group of messages based on their device timestamps. The issue with IMUData is that it groups multiple packets (with timestamps)  together and so it does not have its own timestamp - this requires some special handling that is not yet implemented. However, we are planning on supporting syncing IMU packets through the Sync node.
