### ISSUE TITLE
[BUG] Unable to build due to dependency issue (Hunter)

### ISSUE THREAD

**Issue by ZumWoelkchen** [luxonis/depthai-core#953]
**What happened?**

Attempting to build depthai-core gets stuck on one nlohmann/json dependency.
Hunter tries to fetch [nlohmann_json/3.9.1/f8a20a7/151cbba/a23c16c/da39a3e/basic-deps.DONE](https://raw.githubusercontent.com/cpp-pm/hunter-cache/master/eee2173/nlohmann_json/3.9.1/f8a20a7/151cbba/a23c16c/da39a3e/basic-deps.DONE) but gets a 404 response.

**How to reproduce?**

1. Pull depthai-core to some directory
2. cmake -S. -Bbuild
3. Hunter gets stuck at: -- [hunter] NLOHMANN_JSON_ROOT: /Users/**USERNAME**/.hunter/_Base/cb0ea1f/eee2173/7f91c96/Install (ver.: 3.9.1)

**Comment by moratom** [comment]
@ZumWoelkchen sorry for the issue.

I tried to reproduce on the fresh clone, but couldn't reproduce the issue on:
* Ubuntu 20.04
* Using latest  `main` branch - hash `6628488ef8956f73f1c7bf4c8f1da218ad327a6f`

Which OS and which commit for `depthai-core` are you using?

**Comment by personball** [comment]
Met Same Problem.

Please Consider switch package manager to [microsoft/vcpkg](https://github.com/microsoft/vcpkg)

**Comment by ZumWoelkchen** [comment]
> @ZumWoelkchen sorry for the issue.
> 
> I tried to reproduce on the fresh clone, but couldn't reproduce the issue on:
> 
> * Ubuntu 20.04
> * Using latest  `main` branch - hash `6628488ef8956f73f1c7bf4c8f1da218ad327a6f`
> 
> Which OS and which commit for `depthai-core` are you using?

@moratom
I'm on macOS Sonoma 14.2.1 x86_64 latest commit **6628488e** on branch **main**
I freshly cloned the repo again and deleted the .hunter folder in my user. Still facing the same problem. I spun up a Ubuntu 20.04 installation, tried it on another Mac and yes indeed it does work. So apparently this is a local issue. Any idea what is going on?

Already did `rm -r ~/.hunter`
I'm running CMake 3.25.2

**Comment by ZumWoelkchen** [comment]
Interestingly it worked when configuring with the HUNTER_TLS_VERIFY flag set to OFF.

For anyone else stumbling into this issue:
`cmake -S. -Bbuild -DHUNTER_TLS_VERIFY=OFF`

**Comment by moratom** [comment]
Linking the relevant issue: https://github.com/Homebrew/homebrew-core/issues/158759
