### ISSUE TITLE
[BUG] UVC.hpp not included in nodes.hpp

### ISSUE THREAD

**Issue by tk4218** [luxonis/depthai-core#964]
UVC support was added in release v2.22.0, but it looks like UVC.hpp was never put into nodes.hpp, which makes the UVC node inaccessible when building the pipeline.

Please add UVC.hpp to nodes.hpp (include/depthai/pipeline/nodes.hpp)

**Comment by moratom** [comment]
Added in develop - thanks @asahtik!
